name: 'Deploy to GKE'
description: 'Deploy an image to GKE'
branding:
  color: 'green'
  icon: 'box'
inputs:
  gcr_host:
    description: 'Google Container Registry Host'
    default: 'gcr.io'
  image_name:
    description: 'Docker Image Name'
    required: true
  image_tag:
    description: 'Docker Image Tag'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
